from PyQt4 import QtCore, QtGui
from checkin_inventory import *
from openpyxl import Workbook
import subprocess, os, platform, re, time, sys, openpyxl

save_path = os.path.expanduser('~\Documents\Security Checkin Archive')
save_filename = './SHI_Device_Log_' + time.strftime("%m-%d-%y") + '.xlsx'
active_workbook = os.path.join(save_path, save_filename)

if not os.path.exists(save_path):
    os.makedirs(save_path)

if os.path.isfile(save_path + save_filename):
	wb = openpyxl.load_workbook(active_workbook,)
	ws1 = wb.get_sheet_by_name('Log Archive')

else:
	wb = Workbook()
	ws1 = wb.active
	ws1.title = 'Log Archive'
	labels = ['Name', 'Device', 'Item Description', 'Item Serial #', 'Asset Tag #', 'IN', 'OUT', 'STAY IN']
	ws1.append(labels)
	cd = ws1.column_dimensions
	cd["A"].width = '18'
	cd["B"].width = '30'
	cd["C"].width = '40'
	cd["D"].width = '41'
	cd["E"].width = '15'
	cd["F"].width, cd["G"].width, cd["H"].width = '18', '18', '18'
	wb.save(filename = active_workbook)

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

# GUI program main functions		
		
class Ui_SHICheckIn(QtGui.QMainWindow):

	def __init__(self):
		QtGui.QMainWindow.__init__(self)
		self.setupUi(self)
		
	def open_directory(self):
		os.startfile(save_path)
		
# Check in new registered user ----------------------------------------------v
	def new_submit_chkin(self):
		chkin_new_name_text = str(self.chkin_new_name_in.displayText())
		chkin_new_device_text = str(self.chkin_drpmn_device.currentText())
		chkin_new_serial_text = str(self.chkin_new_serial_in.displayText())
		chkin_new_asset_text = str(self.chkin_new_asset_in.displayText())
		chkin_new_descr_text = str(self.chkin_new_descr_in.displayText())
		chkin_ndata = ( chkin_new_name_text, chkin_new_device_text, chkin_new_descr_text, chkin_new_serial_text, chkin_new_asset_text, time.strftime("%m/%d/%y %H:%M - %p") )
		matching_row_nbr = None
		for rowNum in range(2, ws1.max_row + 1 ):
			log_name = ws1.cell(row=rowNum,column=1).value
			if log_name == chkin_new_name_text:
				matching_row_nbr = rowNum
				break
		if matching_row_nbr is not None:
			ws1.cell(row=matching_row_nbr, column=6).value = str(time.strftime("%m/%d/%y %H:%M - %p"))
			wb.save(filename = active_workbook)
			self.chkin_new_name_in.clear()
			self.chkin_drpmn_device.setCurrentIndex(-1)
			self.chkin_new_serial_in.clear()
			self.chkin_new_asset_in.clear()
			self.chkin_new_descr_in.clear()
		else:
			ws1.append(chkin_ndata)
			wb.save(filename = active_workbook)
			self.chkin_new_name_in.clear()
			self.chkin_drpmn_device.setCurrentIndex(-1)
			self.chkin_new_serial_in.clear()
			self.chkin_new_asset_in.clear()
			self.chkin_new_descr_in.clear()
# End check in new registered user -----------------------------------------------^
	
# Check in regular registered user -----------------------------------------------v
	def chkin_reg_autofill(self, currentIndex):
		if currentIndex >= -1: 
			self.chkin_reg_device_in.setText(var[currentIndex][0])
			self.chkin_reg_serial_in.setText(var[currentIndex][1])
			self.chkin_reg_asset_in.setText(var[currentIndex][2])
			self.chkin_reg_descr_in.setText(var[currentIndex][3])
			
	def reg_submit_chkin(self):
		chkin_reg_name_text = str(self.chkin_drpmn_name.currentText())
		chkin_reg_device_text = str(self.chkin_reg_device_in.displayText())
		chkin_reg_serial_text = str(self.chkin_reg_serial_in.displayText())
		chkin_reg_asset_text = str(self.chkin_reg_asset_in.displayText())
		chkin_reg_descr_text = str(self.chkin_reg_descr_in.displayText())
		chkin_rdata = ( chkin_reg_name_text, chkin_reg_device_text, chkin_reg_descr_text, chkin_reg_serial_text, chkin_reg_asset_text, time.strftime("%m/%d/%y %H:%M - %p") )
		matching_row_nbr = None
		for rowNum in range(2, ws1.max_row + 1 ):
			log_name = ws1.cell(row=rowNum,column=1).value
			if log_name == chkin_reg_name_text:
				matching_row_nbr = rowNum
				break
		if matching_row_nbr is not None:
			ws1.cell(row=matching_row_nbr, column=6).value = str(time.strftime("%m/%d/%y %H:%M - %p"))
			wb.save(filename = active_workbook)
			self.chkin_drpmn_name.setCurrentIndex(-1)
			self.chkin_reg_device_in.clear()
			self.chkin_reg_serial_in.clear()
			self.chkin_reg_asset_in.clear()
			self.chkin_reg_descr_in.clear()
		else:
			ws1.append(chkin_rdata)
			wb.save(filename = active_workbook)
			self.chkin_drpmn_name.setCurrentIndex(-1)
			self.chkin_reg_device_in.clear()
			self.chkin_reg_serial_in.clear()
			self.chkin_reg_asset_in.clear()
			self.chkin_reg_descr_in.clear()
# End check in regular registered user -------------------------------------------^
	
# Check out new registered user --------------------------------------------------v
	def new_submit_chkout(self):
		chkout_new_name_text = str(self.chkout_new_name_in.displayText())
		chkout_new_device_text = str(self.chkout_drpmn_device.currentText())
		chkout_new_serial_text = str(self.chkout_new_serial_in.displayText())
		chkout_new_asset_text = str(self.chkout_new_asset_in.displayText())
		chkout_new_descr_text = str(self.chkout_new_descr_in.displayText())
		chkout_ndata = ( chkout_new_name_text, chkout_new_device_text, chkout_new_descr_text, chkout_new_serial_text, chkout_new_asset_text, '', time.strftime("%m/%d/%y %H:%M - %p"))
		matching_row_nbr = None
		for rowNum in range(2, ws1.max_row + 1 ):
			log_name = ws1.cell(row=rowNum,column=1).value
			if log_name == chkout_new_name_text:
				matching_row_nbr = rowNum
				break
		if matching_row_nbr is not None:
			ws1.cell(row=matching_row_nbr, column=7).value = str(time.strftime("%m/%d/%y %H:%M - %p"))
			wb.save(filename = active_workbook)
			self.chkout_new_name_in.clear()
			self.chkout_drpmn_device.setCurrentIndex(-1)
			self.chkout_new_serial_in.clear()
			self.chkout_new_asset_in.clear()
			self.chkout_new_descr_in.clear()
		else:
			ws1.append(chkout_ndata)
			wb.save(filename = active_workbook)
			self.chkout_new_name_in.clear()
			self.chkout_drpmn_device.setCurrentIndex(-1)
			self.chkout_new_serial_in.clear()
			self.chkout_new_asset_in.clear()
			self.chkout_new_descr_in.clear()
# End check out new registered user ---------------------------------------------^
	
# Check out regular registered user ---------------------------------------------v
	def chkout_reg_autofill(self, currentIndex):
		if currentIndex >= -1: 
			self.chkout_reg_device_in.setText(var[currentIndex][0])
			self.chkout_reg_serial_in.setText(var[currentIndex][1])
			self.chkout_reg_asset_in.setText(var[currentIndex][2])
			self.chkout_reg_descr_in.setText(var[currentIndex][3])

	def reg_submit_chkout(self):
		chkout_reg_name_text = str(self.chkout_drpmn_name.currentText())
		chkout_reg_device_text = str(self.chkout_reg_device_in.displayText())
		chkout_reg_serial_text = str(self.chkout_reg_serial_in.displayText())
		chkout_reg_asset_text = str(self.chkout_reg_asset_in.displayText())
		chkout_reg_descr_text = str(self.chkout_reg_descr_in.displayText())
		chkout_rdata = ( chkout_reg_name_text, chkout_reg_device_text, chkout_reg_descr_text, chkout_reg_serial_text, chkout_reg_asset_text, '', time.strftime("%m/%d/%y %H:%M - %p") )
		matching_row_nbr = None
		for rowNum in range(2, ws1.max_row + 1 ):
			log_name = ws1.cell(row=rowNum,column=1).value
			if log_name == chkout_reg_name_text:
				matching_row_nbr = rowNum
				break
		if matching_row_nbr is not None:
			ws1.cell(row=matching_row_nbr, column=7).value = str(time.strftime("%m/%d/%y %H:%M - %p"))
			wb.save(filename = active_workbook)
			self.chkout_drpmn_name.setCurrentIndex(-1)
			self.chkout_reg_device_in.clear()
			self.chkout_reg_serial_in.clear()
			self.chkout_reg_asset_in.clear()
			self.chkout_reg_descr_in.clear()
		else:
			ws1.append(chkout_rdata)
			wb.save(filename = active_workbook)
			self.chkout_drpmn_name.setCurrentIndex(-1)
			self.chkout_reg_device_in.clear()
			self.chkout_reg_serial_in.clear()
			self.chkout_reg_asset_in.clear()
			self.chkout_reg_descr_in.clear()
# End check out new registered user --------------------------------------------^

	def setupUi(self, SHICheckIn):
		SHICheckIn.setObjectName(_fromUtf8("SHICheckIn"))
		SHICheckIn.resize(1505, 1300)
		self.setWindowIcon(QtGui.QIcon('Security.png'))
		self.centralwidget = QtGui.QWidget(SHICheckIn)
		self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
		self.tabWidget = QtGui.QTabWidget(self.centralwidget)
		self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1501, 1131))
		font = QtGui.QFont()
		font.setPointSize(24)
		self.tabWidget.setFont(font)
		self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
		self.CheckIn = QtGui.QWidget()
		self.CheckIn.setObjectName(_fromUtf8("CheckIn"))
# Check in new registered user ------------------------------------------v
		self.chkin_new_title = QtGui.QLabel(self.CheckIn)
		self.chkin_new_title.setGeometry(QtCore.QRect(10, 10, 761, 51))
		self.chkin_new_title.setMinimumSize(QtCore.QSize(481, 51))
		self.chkin_new_title.setMaximumSize(QtCore.QSize(481, 51))
		self.chkin_new_title.setObjectName(_fromUtf8("chkin_new_title"))	
		self.chkin_new_name = QtGui.QLabel(self.CheckIn)
		self.chkin_new_name.setGeometry(QtCore.QRect(10, 70, 271, 61))
		self.chkin_new_name.setMinimumSize(QtCore.QSize(121, 61))
		self.chkin_new_name.setObjectName(_fromUtf8("chkin_new_name"))
		self.chkin_new_name_in = QtGui.QLineEdit(self.CheckIn)
		self.chkin_new_name_in.setGeometry(QtCore.QRect(300, 70, 1151, 71))
		self.chkin_new_name_in.setMinimumSize(QtCore.QSize(1031, 61))
		self.chkin_new_name_in.setObjectName(_fromUtf8("chkin_new_name_in"))
		self.chkin_new_device = QtGui.QLabel(self.CheckIn)
		self.chkin_new_device.setGeometry(QtCore.QRect(10, 160, 271, 61))
		self.chkin_new_device.setMinimumSize(QtCore.QSize(131, 61))
		self.chkin_new_device.setObjectName(_fromUtf8("chkin_new_device"))
		self.chkin_drpmn_device = QtGui.QComboBox(self.CheckIn)
		self.chkin_drpmn_device.setGeometry(QtCore.QRect(300, 160, 521, 61))
		self.chkin_drpmn_device.setMinimumSize(QtCore.QSize(521, 61))
		self.chkin_drpmn_device.setMaximumSize(QtCore.QSize(521, 61))
		font = QtGui.QFont()
		font.setPointSize(24)
		self.chkin_drpmn_device.setFont(font)
		self.chkin_drpmn_device.setObjectName(_fromUtf8("chkin_drpmn_device"))
		self.chkin_drpmn_device.addItem(_fromUtf8(""))
		self.chkin_drpmn_device.addItem(_fromUtf8(""))
		self.chkin_drpmn_device.addItem(_fromUtf8(""))
		self.chkin_drpmn_device.addItem(_fromUtf8(""))
		self.chkin_drpmn_device.addItem(_fromUtf8(""))
		self.chkin_drpmn_device.addItem(_fromUtf8(""))
		self.chkin_drpmn_device.addItem(_fromUtf8(""))
		self.chkin_drpmn_device.addItem(_fromUtf8(""))
		self.chkin_drpmn_device.addItem(_fromUtf8(""))
		self.chkin_drpmn_device.addItem(_fromUtf8(""))
		self.chkin_drpmn_device.addItem(_fromUtf8(""))
		self.chkin_drpmn_device.setCurrentIndex(-1)
		self.chkin_new_serial = QtGui.QLabel(self.CheckIn)
		self.chkin_new_serial.setGeometry(QtCore.QRect(10, 240, 271, 61))
		self.chkin_new_serial.setMinimumSize(QtCore.QSize(151, 61))
		self.chkin_new_serial.setObjectName(_fromUtf8("chkin_new_serial"))
		self.chkin_new_serial_in = QtGui.QLineEdit(self.CheckIn)
		self.chkin_new_serial_in.setGeometry(QtCore.QRect(300, 240, 391, 71))
		self.chkin_new_serial_in.setMinimumSize(QtCore.QSize(351, 61))
		self.chkin_new_serial_in.setObjectName(_fromUtf8("chkin_new_serial_in"))
		self.chkin_new_asset = QtGui.QLabel(self.CheckIn)
		self.chkin_new_asset.setGeometry(QtCore.QRect(720, 240, 311, 61))
		self.chkin_new_asset.setMinimumSize(QtCore.QSize(211, 61))
		self.chkin_new_asset.setObjectName(_fromUtf8("chkin_new_asset"))
		self.chkin_new_asset_in = QtGui.QLineEdit(self.CheckIn)
		self.chkin_new_asset_in.setGeometry(QtCore.QRect(1050, 240, 401, 71))
		self.chkin_new_asset_in.setMinimumSize(QtCore.QSize(401, 61))
		self.chkin_new_asset_in.setObjectName(_fromUtf8("chkin_new_asset_in"))
		self.chkin_new_descr = QtGui.QLabel(self.CheckIn)
		self.chkin_new_descr.setGeometry(QtCore.QRect(10, 330, 301, 61))
		self.chkin_new_descr.setMinimumSize(QtCore.QSize(201, 61))
		font = QtGui.QFont()
		font.setPointSize(8)
		self.chkin_new_descr.setFont(font)
		self.chkin_new_descr.setObjectName(_fromUtf8("chkin_new_descr"))
		self.chkin_new_descr_in = QtGui.QLineEdit(self.CheckIn)
		self.chkin_new_descr_in.setGeometry(QtCore.QRect(330, 330, 1121, 71))
		self.chkin_new_descr_in.setMinimumSize(QtCore.QSize(951, 61))
		self.chkin_new_descr_in.setObjectName(_fromUtf8("chkin_new_descr_in"))
		self.chkin_new_submit = QtGui.QPushButton(self.CheckIn)
		self.chkin_new_submit.setGeometry(QtCore.QRect(10, 420, 361, 81))
		self.chkin_new_submit.setMinimumSize(QtCore.QSize(231, 61))
		font = QtGui.QFont()
		font.setPointSize(24)
		self.chkin_new_submit.setFont(font)
		self.chkin_new_submit.setObjectName(_fromUtf8("chkin_new_submit"))
		self.chkin_new_submit.clicked.connect(self.new_submit_chkin)
# End check in new registered user ------------------------------------------^
		self.chkin_divider = QtGui.QFrame(self.CheckIn)
		self.chkin_divider.setGeometry(QtCore.QRect(10, 520, 1171, 20))
		self.chkin_divider.setMinimumSize(QtCore.QSize(1171, 20))
		self.chkin_divider.setMaximumSize(QtCore.QSize(1171, 20))
		self.chkin_divider.setFrameShape(QtGui.QFrame.HLine)
		self.chkin_divider.setFrameShadow(QtGui.QFrame.Sunken)
		self.chkin_divider.setObjectName(_fromUtf8("chkin_divider"))
		self.chkin_shi_img = QtGui.QLabel(self.CheckIn)
		self.chkin_shi_img.setGeometry(QtCore.QRect(1190, 470, 261, 171))
		self.chkin_shi_img.setText(_fromUtf8(""))
		self.chkin_shi_img.setPixmap(QtGui.QPixmap(_fromUtf8("shilogo.jpg")))
		self.chkin_shi_img.setScaledContents(True)
		self.chkin_shi_img.setObjectName(_fromUtf8("chkin_shi_img"))
# Check in regular registered user ------------------------------------------v
		self.chkin_reg_title = QtGui.QLabel(self.CheckIn)
		self.chkin_reg_title.setGeometry(QtCore.QRect(10, 560, 861, 51))
		self.chkin_reg_title.setMinimumSize(QtCore.QSize(611, 51))
		self.chkin_reg_title.setMaximumSize(QtCore.QSize(611, 51))
		self.chkin_reg_title.setObjectName(_fromUtf8("chkin_reg_title"))
		self.chkin_reg_name = QtGui.QLabel(self.CheckIn)
		self.chkin_reg_name.setGeometry(QtCore.QRect(10, 630, 271, 61))
		self.chkin_reg_name.setMinimumSize(QtCore.QSize(121, 61))
		self.chkin_reg_name.setObjectName(_fromUtf8("chkin_reg_name"))
		self.chkin_drpmn_name = QtGui.QComboBox(self.CheckIn)
		self.chkin_drpmn_name.setGeometry(QtCore.QRect(300, 630, 521, 61))
		self.chkin_drpmn_name.setMinimumSize(QtCore.QSize(521, 61))
		font = QtGui.QFont()
		font.setPointSize(24)
		self.chkin_drpmn_name.setFont(font)
		self.chkin_drpmn_name.setObjectName(_fromUtf8("chkin_drpmn_name"))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.addItem(_fromUtf8(""))
		self.chkin_drpmn_name.setCurrentIndex(-1)
		self.connect(self.chkin_drpmn_name, QtCore.SIGNAL('currentIndexChanged(int)'), self.chkin_reg_autofill)
		self.chkin_reg_device = QtGui.QLabel(self.CheckIn)
		self.chkin_reg_device.setGeometry(QtCore.QRect(10, 710, 271, 61))
		self.chkin_reg_device.setMinimumSize(QtCore.QSize(131, 61))
		self.chkin_reg_device.setObjectName(_fromUtf8("chkin_reg_device"))
		self.chkin_reg_device_in = QtGui.QLineEdit(self.CheckIn)
		self.chkin_reg_device_in.setGeometry(QtCore.QRect(300, 710, 1151, 71))
		self.chkin_reg_device_in.setMinimumSize(QtCore.QSize(1021, 61))
		self.chkin_reg_device_in.setObjectName(_fromUtf8("chkin_reg_device_in"))
		self.chkin_reg_serial = QtGui.QLabel(self.CheckIn)
		self.chkin_reg_serial.setGeometry(QtCore.QRect(10, 800, 271, 61))
		self.chkin_reg_serial.setMinimumSize(QtCore.QSize(151, 61))
		self.chkin_reg_serial.setObjectName(_fromUtf8("chkin_reg_serial"))
		self.chkin_reg_serial_in = QtGui.QLineEdit(self.CheckIn)
		self.chkin_reg_serial_in.setGeometry(QtCore.QRect(300, 800, 391, 71))
		self.chkin_reg_serial_in.setMinimumSize(QtCore.QSize(351, 61))
		font = QtGui.QFont()
		font.setPointSize(24)
		self.chkin_reg_serial_in.setFont(font)
		self.chkin_reg_serial_in.setObjectName(_fromUtf8("chkin_reg_serial_in"))
		self.chkin_reg_asset = QtGui.QLabel(self.CheckIn)
		self.chkin_reg_asset.setGeometry(QtCore.QRect(720, 800, 321, 61))
		self.chkin_reg_asset.setMinimumSize(QtCore.QSize(211, 61))
		self.chkin_reg_asset.setObjectName(_fromUtf8("chkin_reg_asset"))
		self.chkin_reg_asset_in = QtGui.QLineEdit(self.CheckIn)
		self.chkin_reg_asset_in.setGeometry(QtCore.QRect(1060, 800, 391, 71))
		font = QtGui.QFont()
		font.setPointSize(24)
		self.chkin_reg_asset_in.setFont(font)
		self.chkin_reg_asset_in.setObjectName(_fromUtf8("chkin_reg_asset_in"))
		self.chkin_reg_descr = QtGui.QLabel(self.CheckIn)
		self.chkin_reg_descr.setGeometry(QtCore.QRect(10, 890, 301, 61))
		self.chkin_reg_descr.setMinimumSize(QtCore.QSize(201, 61))
		self.chkin_reg_descr.setObjectName(_fromUtf8("chkin_reg_descr"))
		self.chkin_reg_descr_in = QtGui.QLineEdit(self.CheckIn)
		self.chkin_reg_descr_in.setGeometry(QtCore.QRect(340, 890, 1111, 71))
		self.chkin_reg_descr_in.setMinimumSize(QtCore.QSize(951, 61))
		font = QtGui.QFont()
		font.setPointSize(24)
		font.setBold(False)
		font.setWeight(50)
		self.chkin_reg_descr_in.setFont(font)
		self.chkin_reg_descr_in.setText(_fromUtf8(""))
		self.chkin_reg_descr_in.setObjectName(_fromUtf8("chkin_reg_descr_in"))

		self.chkin_reg_submit = QtGui.QPushButton(self.CheckIn)
		self.chkin_reg_submit.setGeometry(QtCore.QRect(10, 970, 361, 81))
		self.chkin_reg_submit.setMinimumSize(QtCore.QSize(231, 61))
		font = QtGui.QFont()
		font.setPointSize(24)
		self.chkin_reg_submit.setFont(font)
		self.chkin_reg_submit.setObjectName(_fromUtf8("chkin_reg_submit"))
		self.chkin_reg_submit.clicked.connect(self.reg_submit_chkin)
# End check in regular registered user ------------------------------------------^
		self.tabWidget.addTab(self.CheckIn, _fromUtf8(""))
		self.CheckOut = QtGui.QWidget()
		self.CheckOut.setObjectName(_fromUtf8("CheckOut"))
		self.chkout_shi_img = QtGui.QLabel(self.CheckOut)
		self.chkout_shi_img.setGeometry(QtCore.QRect(1190, 470, 261, 171))
		self.chkout_shi_img.setText(_fromUtf8(""))
		self.chkout_shi_img.setPixmap(QtGui.QPixmap(_fromUtf8("shilogo.jpg")))
		self.chkout_shi_img.setScaledContents(True)
		self.chkout_shi_img.setObjectName(_fromUtf8("chkout_shi_img"))
# Check out new registered user ------------------------------------------v
		self.chkout_new_title = QtGui.QLabel(self.CheckOut)
		self.chkout_new_title.setGeometry(QtCore.QRect(10, 10, 481, 51))
		self.chkout_new_title.setMinimumSize(QtCore.QSize(481, 51))
		self.chkout_new_title.setMaximumSize(QtCore.QSize(481, 51))
		self.chkout_new_title.setObjectName(_fromUtf8("chkout_new_title"))
		self.chkout_new_name = QtGui.QLabel(self.CheckOut)
		self.chkout_new_name.setGeometry(QtCore.QRect(10, 70, 271, 61))
		self.chkout_new_name.setMinimumSize(QtCore.QSize(121, 61))
		self.chkout_new_name.setObjectName(_fromUtf8("chkout_new_name"))
		self.chkout_new_name_in = QtGui.QLineEdit(self.CheckOut)
		self.chkout_new_name_in.setGeometry(QtCore.QRect(300, 70, 1151, 71))
		self.chkout_new_name_in.setMinimumSize(QtCore.QSize(1031, 61))
		self.chkout_new_name_in.setObjectName(_fromUtf8("chkout_new_name_in"))
		self.chkout_new_device = QtGui.QLabel(self.CheckOut)
		self.chkout_new_device.setGeometry(QtCore.QRect(10, 160, 271, 61))
		self.chkout_new_device.setMinimumSize(QtCore.QSize(131, 61))
		self.chkout_new_device.setObjectName(_fromUtf8("chkout_new_device"))
		self.chkout_drpmn_device = QtGui.QComboBox(self.CheckOut)
		self.chkout_drpmn_device.setGeometry(QtCore.QRect(300, 160, 521, 61))
		self.chkout_drpmn_device.setMinimumSize(QtCore.QSize(521, 61))
		self.chkout_drpmn_device.setMaximumSize(QtCore.QSize(521, 61))
		self.chkout_drpmn_device.setObjectName(_fromUtf8("chkout_drpmn_device"))
		self.chkout_drpmn_device.addItem(_fromUtf8(""))
		self.chkout_drpmn_device.addItem(_fromUtf8(""))
		self.chkout_drpmn_device.addItem(_fromUtf8(""))
		self.chkout_drpmn_device.addItem(_fromUtf8(""))
		self.chkout_drpmn_device.addItem(_fromUtf8(""))
		self.chkout_drpmn_device.addItem(_fromUtf8(""))
		self.chkout_drpmn_device.addItem(_fromUtf8(""))
		self.chkout_drpmn_device.addItem(_fromUtf8(""))
		self.chkout_drpmn_device.addItem(_fromUtf8(""))
		self.chkout_drpmn_device.addItem(_fromUtf8(""))
		self.chkout_drpmn_device.addItem(_fromUtf8(""))
		self.chkout_drpmn_device.setCurrentIndex(-1)
		self.chkout_new_serial = QtGui.QLabel(self.CheckOut)
		self.chkout_new_serial.setGeometry(QtCore.QRect(10, 240, 271, 61))
		self.chkout_new_serial.setMinimumSize(QtCore.QSize(151, 61))
		self.chkout_new_serial.setObjectName(_fromUtf8("chkout_new_serial"))
		self.chkout_new_serial_in = QtGui.QLineEdit(self.CheckOut)
		self.chkout_new_serial_in.setGeometry(QtCore.QRect(300, 240, 391, 71))
		self.chkout_new_serial_in.setMinimumSize(QtCore.QSize(351, 61))
		self.chkout_new_serial_in.setObjectName(_fromUtf8("chkout_new_serial_in"))
		self.chkout_new_asset = QtGui.QLabel(self.CheckOut)
		self.chkout_new_asset.setGeometry(QtCore.QRect(720, 240, 311, 61))
		self.chkout_new_asset.setMinimumSize(QtCore.QSize(211, 61))
		self.chkout_new_asset.setObjectName(_fromUtf8("chkout_new_asset"))
		self.chkout_new_asset_in = QtGui.QLineEdit(self.CheckOut)
		self.chkout_new_asset_in.setGeometry(QtCore.QRect(1050, 240, 401, 71))
		self.chkout_new_asset_in.setMinimumSize(QtCore.QSize(401, 61))
		self.chkout_new_asset_in.setObjectName(_fromUtf8("chkout_new_asset_in"))
		self.chkout_new_descr = QtGui.QLabel(self.CheckOut)
		self.chkout_new_descr.setGeometry(QtCore.QRect(10, 330, 301, 61))
		self.chkout_new_descr.setMinimumSize(QtCore.QSize(201, 61))
		self.chkout_new_descr.setObjectName(_fromUtf8("chkout_new_descr"))
		self.chkout_new_descr_in = QtGui.QLineEdit(self.CheckOut)
		self.chkout_new_descr_in.setGeometry(QtCore.QRect(330, 330, 1121, 71))
		self.chkout_new_descr_in.setMinimumSize(QtCore.QSize(951, 61))
		self.chkout_new_descr_in.setObjectName(_fromUtf8("chkout_new_descr_in"))
		self.chkout_new_submit = QtGui.QPushButton(self.CheckOut)
		self.chkout_new_submit.setGeometry(QtCore.QRect(10, 420, 361, 81))
		self.chkout_new_submit.setMinimumSize(QtCore.QSize(231, 61))
		self.chkout_new_submit.setObjectName(_fromUtf8("chkout_new_submit"))
		self.chkout_new_submit.clicked.connect(self.new_submit_chkout)
# End check out new registered user ------------------------------------------^
# Check out regular registered user ------------------------------------------v
		self.chkout_reg_title = QtGui.QLabel(self.CheckOut)
		self.chkout_reg_title.setGeometry(QtCore.QRect(10, 560, 611, 51))
		self.chkout_reg_title.setMinimumSize(QtCore.QSize(611, 51))
		self.chkout_reg_title.setMaximumSize(QtCore.QSize(611, 51))
		self.chkout_reg_title.setObjectName(_fromUtf8("chkout_reg_title"))
		self.chkout_reg_name = QtGui.QLabel(self.CheckOut)
		self.chkout_reg_name.setGeometry(QtCore.QRect(10, 630, 271, 61))
		self.chkout_reg_name.setMinimumSize(QtCore.QSize(121, 61))
		self.chkout_reg_name.setObjectName(_fromUtf8("chkout_reg_name"))
		self.chkout_drpmn_name = QtGui.QComboBox(self.CheckOut)
		self.chkout_drpmn_name.setGeometry(QtCore.QRect(300, 630, 521, 61))
		self.chkout_drpmn_name.setMinimumSize(QtCore.QSize(521, 61))
		self.chkout_drpmn_name.setMaximumSize(QtCore.QSize(521, 61))
		self.chkout_drpmn_name.setObjectName(_fromUtf8("chkout_drpmn_name"))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.addItem(_fromUtf8(""))
		self.chkout_drpmn_name.setCurrentIndex(-1)
		self.connect(self.chkout_drpmn_name, QtCore.SIGNAL('currentIndexChanged(int)'), self.chkout_reg_autofill)
		self.chkout_reg_device = QtGui.QLabel(self.CheckOut)
		self.chkout_reg_device.setGeometry(QtCore.QRect(10, 710, 271, 61))
		self.chkout_reg_device.setMinimumSize(QtCore.QSize(131, 61))
		self.chkout_reg_device.setObjectName(_fromUtf8("chkout_reg_device"))
		self.chkout_reg_device_in = QtGui.QLineEdit(self.CheckOut)
		self.chkout_reg_device_in.setGeometry(QtCore.QRect(300, 710, 1151, 71))
		self.chkout_reg_device_in.setMinimumSize(QtCore.QSize(1021, 61))
		self.chkout_reg_device_in.setObjectName(_fromUtf8("chkout_reg_device_in"))
		self.chkout_reg_serial = QtGui.QLabel(self.CheckOut)
		self.chkout_reg_serial.setGeometry(QtCore.QRect(10, 800, 271, 61))
		self.chkout_reg_serial.setMinimumSize(QtCore.QSize(151, 61))
		self.chkout_reg_serial.setObjectName(_fromUtf8("chkout_reg_serial"))
		self.chkout_reg_serial_in = QtGui.QLineEdit(self.CheckOut)
		self.chkout_reg_serial_in.setGeometry(QtCore.QRect(300, 800, 391, 71))
		self.chkout_reg_serial_in.setMinimumSize(QtCore.QSize(351, 61))
		self.chkout_reg_serial_in.setObjectName(_fromUtf8("chkout_reg_serial_in"))
		self.chkout_reg_asset = QtGui.QLabel(self.CheckOut)
		self.chkout_reg_asset.setGeometry(QtCore.QRect(720, 800, 321, 61))
		self.chkout_reg_asset.setMinimumSize(QtCore.QSize(211, 61))
		self.chkout_reg_asset.setObjectName(_fromUtf8("chkout_reg_asset"))
		self.chkout_reg_asset_in = QtGui.QLineEdit(self.CheckOut)
		self.chkout_reg_asset_in.setGeometry(QtCore.QRect(1060, 800, 391, 71))
		self.chkout_reg_asset_in.setObjectName(_fromUtf8("chkout_reg_asset_in"))
		self.chkout_reg_descr = QtGui.QLabel(self.CheckOut)
		self.chkout_reg_descr.setGeometry(QtCore.QRect(10, 890, 301, 61))
		self.chkout_reg_descr.setMinimumSize(QtCore.QSize(201, 61))
		self.chkout_reg_descr.setObjectName(_fromUtf8("chkout_reg_descr"))
		self.chkout_reg_descr_in = QtGui.QLineEdit(self.CheckOut)
		self.chkout_reg_descr_in.setGeometry(QtCore.QRect(340, 890, 1111, 71))
		self.chkout_reg_descr_in.setMinimumSize(QtCore.QSize(951, 61))
		self.chkout_reg_descr_in.setText(_fromUtf8(""))
		self.chkout_reg_descr_in.setObjectName(_fromUtf8("chkout_reg_descr_in"))
		self.chkout_reg_submit = QtGui.QPushButton(self.CheckOut)
		self.chkout_reg_submit.setGeometry(QtCore.QRect(10, 970, 361, 81))
		self.chkout_reg_submit.setMinimumSize(QtCore.QSize(231, 61))
		self.chkout_reg_submit.setObjectName(_fromUtf8("chkout_reg_submit"))
		self.chkout_reg_submit.clicked.connect(self.reg_submit_chkout)
# End check out regular registered user ------------------------------------------^
		self.chkout_divider = QtGui.QFrame(self.CheckOut)
		self.chkout_divider.setGeometry(QtCore.QRect(10, 520, 1171, 20))
		self.chkout_divider.setMinimumSize(QtCore.QSize(1171, 20))
		self.chkout_divider.setMaximumSize(QtCore.QSize(1171, 20))
		self.chkout_divider.setFrameShape(QtGui.QFrame.HLine)
		self.chkout_divider.setFrameShadow(QtGui.QFrame.Sunken)
		self.chkout_divider.setObjectName(_fromUtf8("chkout_divider"))
		self.tabWidget.addTab(self.CheckOut, _fromUtf8(""))
		self.dir_button = QtGui.QPushButton(self.centralwidget)
		self.dir_button.setGeometry(QtCore.QRect(10, 1160, 381, 81))
		self.dir_button.setMinimumSize(QtCore.QSize(361, 47))
		font = QtGui.QFont()
		font.setPointSize(24)
		self.dir_button.setFont(font)
		self.dir_button.setObjectName(_fromUtf8("dir_button"))
		self.dir_button.clicked.connect(self.open_directory)
		self.close_button = QtGui.QPushButton(self.centralwidget)
		self.close_button.setGeometry(QtCore.QRect(400, 1160, 381, 81))
		self.close_button.setMinimumSize(QtCore.QSize(321, 47))
		font = QtGui.QFont()
		font.setPointSize(24)
		self.close_button.setFont(font)
		self.close_button.setObjectName(_fromUtf8("close_button"))
		self.close_button.clicked.connect(QtCore.QCoreApplication.instance().quit)
		SHICheckIn.setCentralWidget(self.centralwidget)
		self.menubar = QtGui.QMenuBar(SHICheckIn)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1505, 21))
		self.menubar.setObjectName(_fromUtf8("menubar"))
		SHICheckIn.setMenuBar(self.menubar)
		self.statusbar = QtGui.QStatusBar(SHICheckIn)
		self.statusbar.setObjectName(_fromUtf8("statusbar"))
		SHICheckIn.setStatusBar(self.statusbar)

		self.retranslateUi(SHICheckIn)
		self.tabWidget.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(SHICheckIn)

	def retranslateUi(self, SHICheckIn):
		SHICheckIn.setWindowTitle(_translate("SHICheckIn", "MainWindow", None))
		self.chkin_new_name.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Name:</span></p></body></html>", None))
		self.chkin_new_descr.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Description:</span></p></body></html>", None))
		self.chkin_new_serial.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Serial #:</span></p></body></html>", None))
		self.chkin_new_asset.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Asset Tag #:</span></p></body></html>", None))
		self.chkin_drpmn_device.setItemText(0, _translate("SHICheckIn", "HP Laptop", None))
		self.chkin_drpmn_device.setItemText(1, _translate("SHICheckIn", "Dell Laptop", None))
		self.chkin_drpmn_device.setItemText(2, _translate("SHICheckIn", "Toshiba Laptop", None))
		self.chkin_drpmn_device.setItemText(3, _translate("SHICheckIn", "Lenovo Laptop", None))
		self.chkin_drpmn_device.setItemText(4, _translate("SHICheckIn", "Apple MacBook", None))
		self.chkin_drpmn_device.setItemText(5, _translate("SHICheckIn", "Samsung Tablet", None))
		self.chkin_drpmn_device.setItemText(6, _translate("SHICheckIn", "Microsoft Surface", None))
		self.chkin_drpmn_device.setItemText(7, _translate("SHICheckIn", "iPad", None))
		self.chkin_drpmn_device.setItemText(8, _translate("SHICheckIn", "iPad Mini", None))
		self.chkin_drpmn_device.setItemText(9, _translate("SHICheckIn", "USB Charger", None))
		self.chkin_drpmn_device.setItemText(10, _translate("SHICheckIn", "Unlisted (See Description)", None))
		self.chkin_new_device.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Device:</span></p></body></html>", None))
		self.chkin_reg_submit.setText(_translate("SHICheckIn", "Check In", None))
		self.chkin_new_title.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">CHECK IN FOR NEW ENTRIES</span></p></body></html>", None))
		self.chkin_reg_title.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">CHECK IN PRESET REGULAR ENTRIES</span></p></body></html>", None))
		self.chkin_reg_descr.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Description:</span></p></body></html>", None))
		self.chkin_reg_name.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Name:</span></p></body></html>", None))
		self.chkin_reg_device.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Device:</span></p></body></html>", None))
		self.chkin_reg_serial.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Serial #:</span></p></body></html>", None))
		self.chkin_reg_asset.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Asset Tag #:</span></p></body></html>", None))
		self.chkin_new_submit.setText(_translate("SHICheckIn", "Check In", None))
		self.chkin_drpmn_name.setItemText(0, _translate("SHICheckIn", "Ali Alloo", None))
		self.chkin_drpmn_name.setItemText(1, _translate("SHICheckIn", "Brian Covela", None))
		self.chkin_drpmn_name.setItemText(2, _translate("SHICheckIn", "Chris Sullo", None))
		self.chkin_drpmn_name.setItemText(3, _translate("SHICheckIn", "Curtis Booker", None))
		self.chkin_drpmn_name.setItemText(4, _translate("SHICheckIn", "Damian Latourette", None))
		self.chkin_drpmn_name.setItemText(5, _translate("SHICheckIn", "Daniel Carreira", None))
		self.chkin_drpmn_name.setItemText(6, _translate("SHICheckIn", "Edward Nunez", None))
		self.chkin_drpmn_name.setItemText(7, _translate("SHICheckIn", "Hector Rivera", None))
		self.chkin_drpmn_name.setItemText(8, _translate("SHICheckIn", "Jason Folmar", None))
		self.chkin_drpmn_name.setItemText(9, _translate("SHICheckIn", "Jose Lopez", None))
		self.chkin_drpmn_name.setItemText(10, _translate("SHICheckIn", "Josue Cardona", None))
		self.chkin_drpmn_name.setItemText(11, _translate("SHICheckIn", "Rhina Cardona", None))
		self.chkin_drpmn_name.setItemText(12, _translate("SHICheckIn", "Keith K", None))
		self.chkin_drpmn_name.setItemText(13, _translate("SHICheckIn", "Kendell Lucas", None))
		self.chkin_drpmn_name.setItemText(14, _translate("SHICheckIn", "Michael Scott", None))
		self.chkin_drpmn_name.setItemText(15, _translate("SHICheckIn", "Nihad Issa", None))
		self.chkin_drpmn_name.setItemText(16, _translate("SHICheckIn", "Oscar Vartanian", None))
		self.chkin_drpmn_name.setItemText(17, _translate("SHICheckIn", "Paul Brew", None))
		self.chkin_drpmn_name.setItemText(18, _translate("SHICheckIn", "Rick Karp", None))
		self.chkin_drpmn_name.setItemText(19, _translate("SHICheckIn", "Rob Harrison", None))
		self.chkin_drpmn_name.setItemText(20, _translate("SHICheckIn", "Rohan Grandeson", None))
		self.chkin_drpmn_name.setItemText(21, _translate("SHICheckIn", "Sean Larson", None))
		self.chkin_drpmn_name.setItemText(22, _translate("SHICheckIn", "Steve Alt", None))
		self.chkin_drpmn_name.setItemText(23, _translate("SHICheckIn", "Thomas O. Dell", None))
		self.chkin_drpmn_name.setItemText(24, _translate("SHICheckIn", "Tishonda Carson", None))
		self.chkin_drpmn_name.setItemText(25, _translate("SHICheckIn", "Tom Mililli", None))
		self.chkin_drpmn_name.setItemText(26, _translate("SHICheckIn", "William Morris", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.CheckIn), _translate("SHICheckIn", "Check In", None))
		self.chkout_reg_device.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-weight:600;\">Device:</span></p></body></html>", None))
		self.chkout_new_submit.setText(_translate("SHICheckIn", "Check Out", None))
		self.chkout_new_title.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-weight:600;\">CHECK IN FOR NEW ENTRIES</span></p></body></html>", None))
		self.chkout_new_device.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-weight:600;\">Device:</span></p></body></html>", None))
		self.chkout_reg_submit.setText(_translate("SHICheckIn", "Check Out", None))
		self.chkout_reg_title.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-weight:600;\">CHECK IN PRESET REGULAR ENTRIES</span></p></body></html>", None))
		self.chkout_new_serial.setToolTip(_translate("SHICheckIn", "<html><head/><body><p>Please enter serial number located on the device.</p></body></html>", None))
		self.chkout_new_serial.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-weight:600;\">Serial #:</span></p></body></html>", None))
		self.chkout_reg_asset.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-weight:600;\">Asset Tag #:</span></p></body></html>", None))
		self.chkout_new_descr.setToolTip(_translate("SHICheckIn", "<html><head/><body><p>If employee/vistor does not have a pre-defined device. Describe the device as accurate as possible.</p></body></html>", None))
		self.chkout_new_descr.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-weight:600;\">Description:</span></p></body></html>", None))
		self.chkout_reg_serial.setToolTip(_translate("SHICheckIn", "<html><head/><body><p>Please enter serial number located on the device.</p></body></html>", None))
		self.chkout_reg_serial.setWhatsThis(_translate("SHICheckIn", "<html><head/><body><p><br/></p></body></html>", None))
		self.chkout_reg_serial.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-weight:600;\">Serial #:</span></p></body></html>", None))
		self.chkout_drpmn_device.setItemText(0, _translate("SHICheckIn", "HP Laptop", None))
		self.chkout_drpmn_device.setItemText(1, _translate("SHICheckIn", "Dell Laptop", None))
		self.chkout_drpmn_device.setItemText(2, _translate("SHICheckIn", "Toshiba Laptop", None))
		self.chkout_drpmn_device.setItemText(3, _translate("SHICheckIn", "Lenovo Laptop", None))
		self.chkout_drpmn_device.setItemText(4, _translate("SHICheckIn", "Apple MacBook", None))
		self.chkout_drpmn_device.setItemText(5, _translate("SHICheckIn", "Samsung Tablet", None))
		self.chkout_drpmn_device.setItemText(6, _translate("SHICheckIn", "Microsoft Surface", None))
		self.chkout_drpmn_device.setItemText(7, _translate("SHICheckIn", "iPad", None))
		self.chkout_drpmn_device.setItemText(8, _translate("SHICheckIn", "iPad Mini", None))
		self.chkout_drpmn_device.setItemText(9, _translate("SHICheckIn", "USB Charger", None))
		self.chkout_drpmn_device.setItemText(10, _translate("SHICheckIn", "Unlisted (See Description)", None))
		self.chkout_reg_name.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-weight:600;\">Name:</span></p></body></html>", None))
		self.chkout_reg_descr.setToolTip(_translate("SHICheckIn", "<html><head/><body><p>If employee/vistor does not have a pre-defined device. Describe the device as accurate as possible.</p></body></html>", None))
		self.chkout_reg_descr.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-weight:600;\">Description:</span></p></body></html>", None))
		self.chkout_drpmn_name.setItemText(0, _translate("SHICheckIn", "Ali Alloo", None))
		self.chkout_drpmn_name.setItemText(1, _translate("SHICheckIn", "Brian Covela", None))
		self.chkout_drpmn_name.setItemText(2, _translate("SHICheckIn", "Chris Sullo", None))
		self.chkout_drpmn_name.setItemText(3, _translate("SHICheckIn", "Curtis Booker", None))
		self.chkout_drpmn_name.setItemText(4, _translate("SHICheckIn", "Damian Latourette", None))
		self.chkout_drpmn_name.setItemText(5, _translate("SHICheckIn", "Daniel Carreira", None))
		self.chkout_drpmn_name.setItemText(6, _translate("SHICheckIn", "Edward Nunez", None))
		self.chkout_drpmn_name.setItemText(7, _translate("SHICheckIn", "Hector Rivera", None))
		self.chkout_drpmn_name.setItemText(8, _translate("SHICheckIn", "Jason Folmar", None))
		self.chkout_drpmn_name.setItemText(9, _translate("SHICheckIn", "Jose Lopez", None))
		self.chkout_drpmn_name.setItemText(10, _translate("SHICheckIn", "Josue Cardona", None))
		self.chkout_drpmn_name.setItemText(11, _translate("SHICheckIn", "Rhina Cardona", None))
		self.chkout_drpmn_name.setItemText(12, _translate("SHICheckIn", "Keith K", None))
		self.chkout_drpmn_name.setItemText(13, _translate("SHICheckIn", "Kendell Lucas", None))
		self.chkout_drpmn_name.setItemText(14, _translate("SHICheckIn", "Michael Scott", None))
		self.chkout_drpmn_name.setItemText(15, _translate("SHICheckIn", "Nihad Issa", None))
		self.chkout_drpmn_name.setItemText(16, _translate("SHICheckIn", "Oscar Vartanian", None))
		self.chkout_drpmn_name.setItemText(17, _translate("SHICheckIn", "Paul Brew", None))
		self.chkout_drpmn_name.setItemText(18, _translate("SHICheckIn", "Rick Karp", None))
		self.chkout_drpmn_name.setItemText(19, _translate("SHICheckIn", "Rob Harrison", None))
		self.chkout_drpmn_name.setItemText(20, _translate("SHICheckIn", "Rohan Grandeson", None))
		self.chkout_drpmn_name.setItemText(21, _translate("SHICheckIn", "Sean Larson", None))
		self.chkout_drpmn_name.setItemText(22, _translate("SHICheckIn", "Steve Alt", None))
		self.chkout_drpmn_name.setItemText(23, _translate("SHICheckIn", "Thomas O. Dell", None))
		self.chkout_drpmn_name.setItemText(24, _translate("SHICheckIn", "Tishonda Carson", None))
		self.chkout_drpmn_name.setItemText(25, _translate("SHICheckIn", "Tom Mililli", None))
		self.chkout_drpmn_name.setItemText(26, _translate("SHICheckIn", "William Morris", None))
		self.chkout_new_asset.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-weight:600;\">Asset Tag #:</span></p></body></html>", None))
		self.chkout_new_name.setText(_translate("SHICheckIn", "<html><head/><body><p><span style=\" font-weight:600;\">Name:</span></p></body></html>", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.CheckOut), _translate("SHICheckIn", "Check Out", None))
		self.dir_button.setText(_translate("SHICheckIn", "Open Directory", None))
		self.close_button.setText(_translate("SHICheckIn", "Close", None))

# Mandatory parameters for proper function of GUI
if __name__ == '__main__':
	app = QtGui.QApplication(sys.argv)
	window = Ui_SHICheckIn()
	window.show()
	sys.exit(app.exec_())