var = [
    ["HP Laptop", "5CD7012GcQ/CNU251BG78", "SHI16410/SHI8053", "None"], # Abdellah Maarouf
    ['None', 'DM767A', 'None', 'None'], #"Abdul Kargbo"
    ['HP Tablet', 'None', 'SHI13064', 'None'], # "Ali Alloo"
    ['Apple iPad/Keboard/Pencil', 'None', 'DMPTF3SNGXPX/FTPTL5WNH6Q8', 'C4MTDP5ZGWTJ'], #"Ana Castillo",
    ["Apple iPad/Keboard/Pencil", "DMPTF2YVGXPX/FTPTLAK7H6Q8/FQFTD4CRGWTJ", "None", "None"], #"Andy Perez", 
    ["Kindle", "GOOL407643021N", "None", "None"], #"Bridget Volker"
	["Lenovo Laptop", "R9PMP8W", "None", "None"], #"Brian Covela"
    ["MacBook Pro/Ipad", "DMP5R35AGXPX/DMPLX6QF4YG", "SHI11203/None", "None"], #"Bryan O\'Neill", 
    ["HP Laptop", "None", "SHI11158", "None"], #"Carl Anderson",
    ["HP Laptop", "None", "SHI12695", "None"], #"Carolyne Eustice",
	["HP Laptop","None", "SHI16673","None"], #"Charles Marr",
    ["HP Laptop", "5CD7164PGX", "SHI16866", "None"], #"Chris Lopez", 
    ["HP Laptop","None", "SHI10835","None"], #"Chris Sabella", 
    ["HP Laptop", "None", "SHI13012", "None"], #"Chris Sullo", 
	["HP Laptop", "None", "SHI13970", "None"], #"Christie Anderson", 
	["HP Laptop", "None", "SHI9810", "None"], #"Christie Talorico", 
    ["iPad Mini 4/HP Laptop", "F9FQXIEQGHMH", "SHI14136", "None"], #"Curtis Booker", 
    ["HP Laptop & Mouse", "None", "SHI9892", "None"], #"Damian Latourette", 
    ["Samsung Tablet", "RF2G704W7RR", "None", "None"], #"Daniel Carreira", 
    ["iPad/Keboard/Pencil", "DMPTF1BHGXPX,FTPTM1P3H6Q8,C4MTDE79GWTJ", "None"], #"Daniel Mercado", 
    ["HP Laptop", "None", "SHI16257", "None"], #"David Gerson", 
    ["None", "5CG51900DP", "SHI13035", "None"], #"Dora Rodriguez", 
    ["HP Laptop & USB C Cable", "None", "SHI16411", "None"], #"Edward Nunez", 
	["None", "VAWLOO267G345", "None", "None"], #"Eric Flores",
    ["HP Laptop", "None", "SHI10102", "None"], #"Eric Penderson", 
    ["Toshiba Laptop", "None", "7F114811H", "None"], #"Eric Severence", 
    ["Apple iPad/Keboard/Pencil", "DMPTD676GXPX,FTPTL8RYH6Q8,FQFTD4HCGWTJ", "None", "None"], #"Emee Tupino", 
	["HP Laptop", "None", "SSHI16681", "None"], #"Ezequial Vasquez", 
    ["HP Laptop", "None", "SHI16680", "None"], #"Faisal Mohammad", 
    ["HP Laptop", "None", "SHI2867", "None"], #"Felipa Cousens", 
    ["None", "None", "US2187817", "None"], #Hank Tullis", 
    ["HP Laptop & Charger", "None", "SHI13179", "None"], #"Hector Rivera", 
    ["HP Laptop", "None", "SHI122878", "None"], #"Huan Ching Liao", 
    ["HP Laptop", "None", "SHI10226", "None"], #"James Dodge", 
    ["Honeywell CT50", "Panasonic FZ-1", "None", "None"], #"Jason Folmar", 
	["HP Laptop", "None", "SHI16678", "None"], #"Jeffrey Diggs", 
    ["IPAD", "DMPQMBE8GEWQ", "None", "None"], #"John Giftus", 
    ["Dell Laptop", "7E10547OH", "None", "None"], #"John Popovich 
    ["HP Laptop", "5CD7164PG3", "SHI16683", "None"], #"Jordan Hriniak", 
    ["Patriot Harddrive", "PCGT11255", "None", "None"], #"Jose Lopez", 
    ["JBL Speaker/Alienware Laptop", "TL0284HG/DFYH362", "None", "None"],  #"Josue Cardona", 
    ["HP Laptop", "SCD7164PPO", "None", "None"], #"Justin Rindler", 
    ["HP Laptop", "None", "SHI12722", "None"],  #"Keith K", 
    ["HP Laptop", "None", "SHI16821", "None"], #"Keith Walker", 
    ["iPad", "DMPVG2YFHP51", "None", "None"], #"Kendell Lucas", 
    ["HP Laptop", "None", "SHI16409", "None"], #"Kenny Hutchinson",  
	["None", "XAW10025989396", "None", "None"], #"Kotey Ashie",  
	["HP Laptop", "None", "SHI12213", "None"], #"Kyle Burke",
    ["HP Laptop", "None", "SHI9810", "None"], #"Kristy Talorico", 
	["None", "F9FMX32YFCM6", "None", "None"], #"Kyle Volker",
    ["Toshiba Laptop", "8G165723H", "None", "None"], #"Lee Seaman", 
    ["HP Laptop", "None", "SHI16272", "None"], #"Mark Van Kleef", 
    ["HP Laptop", "None", "SHI16170", "None"], #"Michael Scott", 
    ["HP Laptop", "None", "SHI16682", "None"], #"Michael Pepe", 
    ["Dell", "7F04313H", "None", "None"], #"Mike Finley", 
    ["Toshiba Laptop", "HC50G12/3QTD4Q1", "None", "None"], #"Mike Milano", 
    ["HP Laptop", "5CD7164PH2", "SHI16676", "None"], #"Mudit Bhatt", 
    ["HP Laptop", "None", "SHI14114", "None"], #"Nicole Dejesus", 
    ["HP Laptop", "None", "SHI12589", "None"], #"Nicholas Prociuk", 
    ["iPad", "None", "CONFIG-1112", "None"], #"Nihad Issa", 
    ["HP Laptop", "None", "SHI131628", "None"], #"Oscar Vartanian",
	["None", "RF2F6136QYV", "None", "None"],  #"Patrick Isitua", 
    ["Toshiba Laptop", "7F052102H", "None", "None"],  #"Paul Brew", 
    ["HP Laptop", "DMP5K398GPX", "SHI13805", "None"],  #"Paul Coffey", 
    ["HP Laptop", "None", "SHI18414", "None"],  #"Peter Zhu", 
	["Dell", "GKZC452", "None", "None"],  #"Rashi Dillard", 
    ["HP Laptop", "None", "SHI13847", "None"], #"Rick Karp", 
    ["HP Laptop,cables", "None", "SHI8646", "None"], #"Rob Harrison",
	["DELL", "BHTUP32", "None", "None"], #"Robert Button",
    ["Apple MacBook/Powercord", "CO2HM9XFDTY3", "None", "None"], #"Rohan Grandeson",
	["HP LAPTOP MACBOOK/ IBM", "CLMP4UWPDTY3/GCG25IBM", "SHI16540", "None"], #"Ronald Lofton",
    ["HP Laptop", "None", "SHI16872", "None"], #"Ryan Bowen",  
    ["Toshiba/Dell", "7E064848H", "None", "None"], #"Scott Lane", 
    ["ASETT", "516320", "None", "None"], #"Sean Larson",
	["HP Laptop", "None", "SHI16686", "None"], #"Shantasia Cooper",
    ["HP Laptop", "SCD7155ZC1", "SHI16632" , "None"], #"Shawn Sabino", 
    ["HP Laptop", "None", "SHI14000", "None"], #"Steve Alt", 
	["HP Laptop", "None", "SHI18747", "None"], #"Ted Klein",
    ["HP Laptop", "5CD7012GCM", "SHI16412", "None"], #"Terence Mallory", 
    ["2 TB Harddrive", "None", "None", "None"], #"Thomas O. Dell", 
    ["Lenovo Laptop", "WKSP000420E2TC", "None", "None"], #"Tishonda Carson", 
    ["HP Laptop", "None", "SHI10092", "None"], #"Tom Mililli", 
    ["Lenovo Laptop, 9 USB", "PK07ER1", "None"], #"William Morris", 
    ["HP Laptop", "None", "SHI16492", "None"], #"Yomi Idris", 
	["HP Laptop", "None", "SHI8747", "None"], #"Younes El Hatimi",
    ["None", "584048-001", "None", "None"] #"Yurity Stus", 
    ]