var = [("Abdellah", "Maarouf", "HP Laptop", "5CD7012GcQCNU251BG78", "SHI16410/SHI8053"),
    ("Abdul", "Kargbo", "None", "DM767A", "None"),
    ("Ali", "Alloo", "HP Tablet", "None", "SHI13064"),
    ("Ana", "Castillo", "Apple iPad", "DMPTF3SNGXPX", "", "Keboard", "TPTL5WNH6Q8", "", "Pencil", "C4MTDP5ZGWTJ", "" ), 
    ("Andy", "Perez", "Apple iPad", "DMPTF2YVGXPX", "", "Keboard", "FTPTLAK7H6Q8", "", "Pencil", "FQFTD4CRGWTJ", ""), 
    ("Bridget", "Volker", "Kindle", "GOOL407643021N", "None"), 
	("Brian", "Covela", "Lenovo Laptop", "R9PMP8W", "None"), 
    ("Bryan", "O\'Neil", "MacBook Pro", "DMP5R35AGXPX", "SHI11203", "Ipad", "DMPLX6QF4YG", ""), 
    ("Carl", "Anderson", "HP Laptop", "None", "SHI11158"), 
    ("Carolyne", "Eustice", "HP Laptop", "None", "SHI12695"), 
	("Charles", "Marr", "HP Laptop","None", "SHI16673"), 
    ("Chris", "Lopez",  "HP Laptop", "5CD7164PGX", "SHI16866"), 
    ("Chris", "Sabella", "HP Laptop","None", "SHI10835"),  
    ("Chris", "Sullo", "HP Laptop", " None", "SHI13012"),  
	("Christie", "Anderson", "HP Laptop", "None", "SHI13970"),  
	("Christie", "Talorico", "HP Laptop", "None", "SHI9810"),  
    ("Curtis", "Booker", "iPad Mini 4/HP Laptop", "F9FQXIEQGHMH", "SHI14136"),  
    ("Damian", "Latourette", "HP Laptop & Mouse", "None", "SHI9892"),  
    ("Daniel", "Carreira", "Samsung Tablet", "RF2G704W7RR", "None"),  
    ("Daniel", "Mercado", "iPad", "DMPTF1BHGXPX", "", "Keboard", "FTPTM1P3H6Q8", "", "Pencil", "C4MTDE79GWTJ", ""),  
    ("David", "Gerson", "HP Laptop", "None", "SHI16257"),  
    ("Dora", "Rodriguez", "None", "5CG51900DP", "SHI13035"),  
    ("Edward", "Nunez", "HP Laptop & USB C Cable", "None", "SHI16411", "None"),  
	("Eric", "Flores", "None", "VAWLOO267G345", "None", "None"), 
    ("Eric", "Penderson", "HP Laptop", "None", "SHI10102", "None"),  
    ("Eric", "Severence", "Toshiba Laptop", "None", "7F114811H", "None"),  
    ("Emee", "Tupino",  "Apple iPad/Keboard/Pencil", "DMPTD676GXPX,FTPTL8RYH6Q8,FQFTD4HCGWTJ", "None", "None"), 
	("Ezequial", "Vasquez",  "HP Laptop", "None", "SSHI16681", "None"), 
    ("Faisal", "Mohammad",  "HP Laptop", "None", "SHI16680", "None"), 
    ("Felipa", "Cousens", "HP Laptop", "None", "SHI2867", "None"),  
    ("Hank", "Tullis", "None", "None", "US2187817", "None"), 
    ("Hector", "Rivera", "HP Laptop & Charger", "None", "SHI13179", "None"),  
    ("Huan", "Ching Liao", "HP Laptop", "None", "SHI122878", "None"),  
    ("James", "Dodge", "HP Laptop", "None", "SHI10226", "None"),  
    ("Jason", "Folmar", "Honeywell CT50", "Panasonic FZ-1", "None", "None"),  
	("Jeffrey", "Diggs", "HP Laptop", "None", "SHI16678", "None"),  
    ("John", "Giftus", "IPAD", "DMPQMBE8GEWQ", "None", "None"),  
    ("John", "Popovich", "Dell Laptop", "7E10547OH", "None", "None"),  
    ("Jordan", "Hriniak", "HP Laptop", "5CD7164PG3", "SHI16683", "None"),  
    ("Jose", "Lopez", "Patriot Harddrive", "PCGT11255", "None", "None"),  
    ("Josue", "Cardona", "JBL Speaker/Alienware Laptop", "TL0284HG/DFYH362", "None", "None"),   
    ("Justin", "Rindler",  "HP Laptop", "SCD7164PPO", "None", "None"), 
    ("Keith", "K", "HP Laptop", "None", "SHI12722", "None"),   
    ("Keith", "Walker", "HP Laptop", "None", "SHI16821", "None"),  
    ("Kendell", "Lucas", "iPad", "DMPVG2YFHP51", "None", "None"),  
    ("Kenny", "Hutchinson", "HP Laptop", "None", "SHI16409", "None"),   
	("Kotey", "Ashie", "None", "XAW10025989396", "None", "None"),   
	("Kyle", "Burke", "HP Laptop", "None", "SHI12213", "None"), 
    ("Kristy", "Talorico", "HP Laptop", "None", "SHI9810", "None"),  
	("Kyle", "Volker", "None", "F9FMX32YFCM6", "None", "None"), 
    ("Lee", "Seaman", "Toshiba Laptop", "8G165723H", "None", "None"),  
    ("Mark", "Van Kleef", "HP Laptop", "None", "SHI16272", "None"),  
    ("Michael", "Scott", "HP Laptop", "None", "SHI16170", "None"),  
    ("Michael", "Pepe", "HP Laptop", "None", "SHI16682", "None"),  
    ("Mike", "Finley", "Dell", "7F04313H", "None", "None"),  
    ("Mike", "Milano", "Toshiba Laptop", "HC50G12/3QTD4Q1", "None", "None"),  
    ("Mudit", "Bhatt", "HP Laptop", "5CD7164PH2", "SHI16676", "None"),  
    ("Nicole", "Dejesus", "HP Laptop", "None", "SHI14114", "None"),  
    ("Nicholas", "Prociuk", "HP Laptop", "None", "SHI12589", "None"),  
    ("Nihad", "Issa", "iPad", "None", "CONFIG-1112", "None"),  
    ("Omer", "Vukelj", "HP Laptp", "5CD7164PK1", "SHI16674", "None"),
    ("Oscar", "Vartanian", "HP Laptop", "None", "SHI131628", "None"), 
	("Patrick", "Isitua", "None", "RF2F6136QYV", "None", "None"),   
    ("Paul", "Brew", "Toshiba Laptop", "7F052102H", "None", "None"),   
    ("Paul", "Coffey",  "HP Laptop", "DMP5K398GPX", "SHI13805", "None"),  
    ("Peter", "Zhu", "HP Laptop", "None", "SHI18414", "None"), 
	("Rashi", "Dillard", "Dell", "GKZC452", "None", "None"),   
    ("Rick", "Karp", "HP Laptop", "None", "SHI13847", "None"),  
    ("Rob", "Harrison", "HP Laptop,cables", "None", "SHI8646", "None"), 
	("Robert", "Button", "DELL", "BHTUP32", "None", "None"), 
    ("Rohan", "Grandeson", "Apple MacBook/Powercord", "CO2HM9XFDTY3", "None", "None"), 
	("Ronald", "Lofton", "HP LAPTOP MACBOOK/ IBM", "CLMP4UWPDTY3/GCG25IBM", "SHI16540", "None"), 
    ("Ryan", "Bowen", "HP Laptop", "None", "SHI16872", "None"),   
    ("Scott", "Lane", "Toshiba/Dell", "7E064848H", "None", "None"),  
    ("Sean", "Larson", "ASETT", "516320", "None", "None"), 
	("Shantasia", "Cooper", "HP Laptop", "None", "SHI16686", "None"), 
    ("Shawn", "Sabino", "HP Laptop", "SCD7155ZC1", "SHI16632" , "None"),  
    ("Steve", "Alt", "HP Laptop", "None", "SHI14000", "None"),  
	("Ted", "Klein", "HP Laptop", "None", "SHI18747", "None"), 
    ("Terence", "Mallory", "HP Laptop", "5CD7012GCM", "SHI16412", "None"),  
    ("Thomas", "O. Dell", "2 TB Harddrive", "None", "None", "None"), 
    ("Tishonda", "Carson", "Lenovo Laptop", "WKSP000420E2TC", "None", "None"),  
    ("Tom", "Mililli", "HP Laptop", "None", "SHI10092", "None"),  
    ("William", "Morris", "Lenovo Laptop, 9 USB", "PK07ER1", "None"),  
    ("Yomi", "Idris", "HP Laptop", "None", "SHI16492", "None"),  
	("Younes", "El Hatimi", "HP Laptop", "None", "SHI8747", "None"), 
    ("Yurity", "Stus" "None", "584048-001", "None", "None")]