from PyQt4 import QtCore, QtGui
import core


try:

    _fromUtf8 = QtCore.QString.fromUtf8

except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):

        return QtGui.QApplication.translate(context, text, disambig, _encoding)

except AttributeError:

	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig)

class Validator(QtGui.QValidator):
	def validate(self, string, pos):
		string.replace(0, string.count(), string.toUpper())
		return QtGui.QValidator.Acceptable, pos

class Ui_BYODChkn(QtGui.QMainWindow):

	def __init__(self):
		QtGui.QMainWindow.__init__(self)
		self.setupUi(self)

# End check out new registered user --------------------------------------------^
	def setupUi(self, byodchkn):
		byodchkn.setObjectName(_fromUtf8("byodchkn"))
		byodchkn.resize(1291, 866)
		byodchkn.setMinimumSize(QtCore.QSize(1291, 866))
		byodchkn.setMaximumSize(QtCore.QSize(1291, 866))
		self.setWindowIcon(QtGui.QIcon('images\Security.png'))
		self.centralwidget = QtGui.QWidget(byodchkn)
		self.centralwidget.setMinimumSize(QtCore.QSize(1291, 825))
		self.centralwidget.setMaximumSize(QtCore.QSize(1291, 825))
		self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
		self.tabWidget = QtGui.QTabWidget(self.centralwidget)
		self.tabWidget.setGeometry(QtCore.QRect(10, 10, 931, 761))
		self.tabWidget.setMinimumSize(QtCore.QSize(931, 761))
		font = QtGui.QFont()
		font.setPointSize(18)
		self.tabWidget.setFont(font)
		self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
		self.tab = QtGui.QWidget()
		self.tab.setObjectName(_fromUtf8("tab"))
# Check in new registered user ------------------------------------------v
		self.chkin_new_title = QtGui.QLabel(self.tab)
		self.chkin_new_title.setGeometry(QtCore.QRect(30, 10, 602, 40))
		self.chkin_new_title.setMinimumSize(QtCore.QSize(602, 40))
		font = QtGui.QFont()
		font.setPointSize(25)
		font.setBold(True)
		font.setWeight(75)
		self.chkin_new_title.setFont(font)
		self.chkin_new_title.setObjectName(_fromUtf8("chkin_new_title"))
		self.chkin_new_name = QtGui.QLabel(self.tab)
		self.chkin_new_name.setGeometry(QtCore.QRect(30, 70, 89, 33))
		self.chkin_new_name.setMinimumSize(QtCore.QSize(89, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkin_new_name.setFont(font)
		self.chkin_new_name.setObjectName(_fromUtf8("chkin_new_name"))
		self.chkin_new_name_in = QtGui.QLineEdit(self.tab)
		self.chkin_new_name_in.setGeometry(QtCore.QRect(140, 70, 761, 39))
		self.chkin_new_name_in.setMinimumSize(QtCore.QSize(761, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkin_new_name_in.setFont(font)
		self.chkin_new_name_in.setObjectName(_fromUtf8("chkin_new_name_in"))
		self.validator = Validator(self)
		self.chkin_new_name_in.setValidator(self.validator)
		self.chkin_new_device = QtGui.QLabel(self.tab)
		self.chkin_new_device.setGeometry(QtCore.QRect(30, 130, 100, 33))
		self.chkin_new_device.setMinimumSize(QtCore.QSize(100, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkin_new_device.setFont(font)
		self.chkin_new_device.setObjectName(_fromUtf8("chkin_new_device"))
		self.chkin_drpmn_device = QtGui.QComboBox(self.tab)
		self.chkin_drpmn_device.setGeometry(QtCore.QRect(150, 130, 351, 39))
		self.chkin_drpmn_device.setMinimumSize(QtCore.QSize(351, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkin_drpmn_device.setFont(font)
		self.chkin_drpmn_device.setObjectName(_fromUtf8("chkin_drpmn_device"))
		self.chkin_drpmn_device.addItem(_fromUtf8(""))
		self.chkin_drpmn_device.setCurrentIndex(-1)
		self.chkin_new_serial = QtGui.QLabel(self.tab)
		self.chkin_new_serial.setGeometry(QtCore.QRect(30, 190, 117, 33))
		self.chkin_new_serial.setMinimumSize(QtCore.QSize(117, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkin_new_serial.setFont(font)
		self.chkin_new_serial.setObjectName(_fromUtf8("chkin_new_serial"))
		self.chkin_new_serial_in = QtGui.QLineEdit(self.tab)
		self.chkin_new_serial_in.setGeometry(QtCore.QRect(170, 190, 252, 39))
		self.chkin_new_serial_in.setMinimumSize(QtCore.QSize(252, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkin_new_serial_in.setFont(font)
		self.chkin_new_serial_in.setObjectName(_fromUtf8("chkin_new_serial_in"))
		self.chkin_new_serial_in.setValidator(self.validator)
		self.chkin_new_asset = QtGui.QLabel(self.tab)
		self.chkin_new_asset.setGeometry(QtCore.QRect(440, 190, 171, 33))
		self.chkin_new_asset.setMinimumSize(QtCore.QSize(171, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkin_new_asset.setFont(font)
		self.chkin_new_asset.setObjectName(_fromUtf8("chkin_new_asset"))
		self.chkin_new_asset_in = QtGui.QLineEdit(self.tab)
		self.chkin_new_asset_in.setGeometry(QtCore.QRect(630, 190, 271, 39))
		self.chkin_new_asset_in.setMinimumSize(QtCore.QSize(271, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkin_new_asset_in.setFont(font)
		self.chkin_new_asset_in.setObjectName(_fromUtf8("chkin_new_asset_in"))
		self.chkin_new_asset_in.setValidator(self.validator)
		self.chkin_new_descr = QtGui.QLabel(self.tab)
		self.chkin_new_descr.setGeometry(QtCore.QRect(30, 250, 164, 33))
		self.chkin_new_descr.setMinimumSize(QtCore.QSize(164, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkin_new_descr.setFont(font)
		self.chkin_new_descr.setObjectName(_fromUtf8("chkin_new_descr"))
		self.chkin_new_descr_in = QtGui.QLineEdit(self.tab)
		self.chkin_new_descr_in.setGeometry(QtCore.QRect(210, 250, 691, 39))
		self.chkin_new_descr_in.setMinimumSize(QtCore.QSize(691, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkin_new_descr_in.setFont(font)
		self.chkin_new_descr_in.setObjectName(_fromUtf8("chkin_new_descr_in"))
		self.chkin_new_descr_in.setValidator(self.validator)
		self.chkin_new_submit = QtGui.QPushButton(self.tab)
		self.chkin_new_submit.setGeometry(QtCore.QRect(30, 300, 127, 37))
		self.chkin_new_submit.setMinimumSize(QtCore.QSize(127, 37))
		self.chkin_new_submit.setObjectName(_fromUtf8("chkin_new_submit"))
		self.chkin_new_submit.clicked.connect(core.new_submit_chkin)
# End check in new registered user ------------------------------------------^
		self.chkin_divider = QtGui.QFrame(self.tab)
		self.chkin_divider.setGeometry(QtCore.QRect(10, 350, 911, 16))
		self.chkin_divider.setMinimumSize(QtCore.QSize(911, 16))
		self.chkin_divider.setFrameShape(QtGui.QFrame.HLine)
		self.chkin_divider.setFrameShadow(QtGui.QFrame.Sunken)
		self.chkin_divider.setObjectName(_fromUtf8("chkin_divider"))
# Check in regular registered user ------------------------------------------v
		self.chkin_reg_title = QtGui.QLabel(self.tab)
		self.chkin_reg_title.setGeometry(QtCore.QRect(30, 380, 700, 40))
		self.chkin_reg_title.setMinimumSize(QtCore.QSize(700, 40))
		font = QtGui.QFont()
		font.setPointSize(25)
		font.setBold(True)
		font.setWeight(75)
		self.chkin_reg_title.setFont(font)
		self.chkin_reg_title.setObjectName(_fromUtf8("chkin_reg_title"))
		self.chkin_reg_name = QtGui.QLabel(self.tab)
		self.chkin_reg_name.setGeometry(QtCore.QRect(30, 440, 89, 33))
		self.chkin_reg_name.setMinimumSize(QtCore.QSize(89, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkin_reg_name.setFont(font)
		self.chkin_reg_name.setObjectName(_fromUtf8("chkin_reg_name"))
		self.chkin_drpmn_name = QtGui.QComboBox(self.tab)
		self.chkin_drpmn_name.setGeometry(QtCore.QRect(140, 440, 351, 39))
		self.chkin_drpmn_name.setMinimumSize(QtCore.QSize(351, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkin_drpmn_name.setFont(font)
		self.chkin_drpmn_name.setObjectName(_fromUtf8("chkin_drpmn_name"))
		self.chkin_drpmn_name.setCurrentIndex(-1)
		self.connect(self.chkin_drpmn_name, QtCore.SIGNAL('currentIndexChanged(int)'), core.chkin_reg_autofill)
		self.chkin_reg_device = QtGui.QLabel(self.tab)
		self.chkin_reg_device.setGeometry(QtCore.QRect(30, 500, 100, 33))
		self.chkin_reg_device.setMinimumSize(QtCore.QSize(100, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkin_reg_device.setFont(font)
		self.chkin_reg_device.setObjectName(_fromUtf8("chkin_reg_device"))
		self.chkin_reg_device_in = QtGui.QLineEdit(self.tab)
		self.chkin_reg_device_in.setGeometry(QtCore.QRect(150, 500, 741, 39))
		self.chkin_reg_device_in.setMinimumSize(QtCore.QSize(741, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkin_reg_device_in.setFont(font)
		self.chkin_reg_device_in.setObjectName(_fromUtf8("chkin_reg_device_in"))
		self.chkin_reg_device_in.setValidator(self.validator)
		self.chkin_reg_serial = QtGui.QLabel(self.tab)
		self.chkin_reg_serial.setGeometry(QtCore.QRect(30, 560, 117, 33))
		self.chkin_reg_serial.setMinimumSize(QtCore.QSize(117, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkin_reg_serial.setFont(font)
		self.chkin_reg_serial.setObjectName(_fromUtf8("chkin_reg_serial"))
		self.chkin_reg_serial_in = QtGui.QLineEdit(self.tab)
		self.chkin_reg_serial_in.setGeometry(QtCore.QRect(170, 560, 261, 39))
		self.chkin_reg_serial_in.setMinimumSize(QtCore.QSize(261, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkin_reg_serial_in.setFont(font)
		self.chkin_reg_serial_in.setObjectName(_fromUtf8("chkin_reg_serial_in"))
		self.chkin_reg_serial_in.setValidator(self.validator)
		self.chkin_reg_asset = QtGui.QLabel(self.tab)
		self.chkin_reg_asset.setGeometry(QtCore.QRect(450, 560, 171, 33))
		self.chkin_reg_asset.setMinimumSize(QtCore.QSize(171, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkin_reg_asset.setFont(font)
		self.chkin_reg_asset.setObjectName(_fromUtf8("chkin_reg_asset"))
		self.chkin_reg_asset_in = QtGui.QLineEdit(self.tab)
		self.chkin_reg_asset_in.setGeometry(QtCore.QRect(640, 560, 251, 39))
		self.chkin_reg_asset_in.setMinimumSize(QtCore.QSize(251, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkin_reg_asset_in.setFont(font)
		self.chkin_reg_asset_in.setObjectName(_fromUtf8("chkin_reg_asset_in"))
		self.chkin_reg_asset_in.setValidator(self.validator)
		self.chkin_reg_descr = QtGui.QLabel(self.tab)
		self.chkin_reg_descr.setGeometry(QtCore.QRect(30, 620, 164, 33))
		self.chkin_reg_descr.setMinimumSize(QtCore.QSize(164, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkin_reg_descr.setFont(font)
		self.chkin_reg_descr.setObjectName(_fromUtf8("chkin_reg_descr"))
		self.chkin_reg_descr_in = QtGui.QLineEdit(self.tab)
		self.chkin_reg_descr_in.setGeometry(QtCore.QRect(210, 620, 681, 39))
		self.chkin_reg_descr_in.setMinimumSize(QtCore.QSize(681, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkin_reg_descr_in.setFont(font)
		self.chkin_reg_descr_in.setObjectName(_fromUtf8("chkin_reg_descr_in"))
		self.chkin_reg_descr_in.setValidator(self.validator)
		self.chkin_reg_submit = QtGui.QPushButton(self.tab)
		self.chkin_reg_submit.setGeometry(QtCore.QRect(30, 670, 127, 37))
		self.chkin_reg_submit.setMinimumSize(QtCore.QSize(127, 37))
		self.chkin_reg_submit.setObjectName(_fromUtf8("chkin_reg_submit"))
		self.chkin_reg_submit.clicked.connect(core.reg_submit_chkin)
# End check in regular registered user ------------------------------------------^
# Check out new registered user -------------------------------------------------v
		self.tabWidget.addTab(self.tab, _fromUtf8(""))
		self.tab_2 = QtGui.QWidget()
		self.tab_2.setObjectName(_fromUtf8("tab_2"))
		self.chkout_new_title = QtGui.QLabel(self.tab_2)
		self.chkout_new_title.setGeometry(QtCore.QRect(30, 10, 630, 40))
		font = QtGui.QFont()
		font.setPointSize(25)
		font.setBold(True)
		font.setWeight(75)
		self.chkout_new_title.setFont(font)
		self.chkout_new_title.setObjectName(_fromUtf8("chkout_new_title"))
		self.chkout_new_name = QtGui.QLabel(self.tab_2)
		self.chkout_new_name.setGeometry(QtCore.QRect(30, 70, 89, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkout_new_name.setFont(font)
		self.chkout_new_name.setObjectName(_fromUtf8("chkout_new_name"))
		self.chkout_new_name_in = QtGui.QLineEdit(self.tab_2)
		self.chkout_new_name_in.setGeometry(QtCore.QRect(140, 70, 761, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkout_new_name_in.setFont(font)
		self.chkout_new_name_in.setObjectName(_fromUtf8("chkout_new_name_in"))
		self.chkout_new_name_in.setValidator(self.validator)
		self.chkout_new_device = QtGui.QLabel(self.tab_2)
		self.chkout_new_device.setGeometry(QtCore.QRect(30, 130, 100, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkout_new_device.setFont(font)
		self.chkout_new_device.setObjectName(_fromUtf8("chkout_new_device"))
		self.chkout_drpmn_device = QtGui.QComboBox(self.tab_2)
		self.chkout_drpmn_device.setGeometry(QtCore.QRect(150, 130, 351, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkout_drpmn_device.setFont(font)
		self.chkout_drpmn_device.setObjectName(_fromUtf8("chkout_drpmn_device"))
		self.chkout_drpmn_device.setCurrentIndex(-1)
		self.chkout_new_serial = QtGui.QLabel(self.tab_2)
		self.chkout_new_serial.setGeometry(QtCore.QRect(30, 190, 117, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkout_new_serial.setFont(font)
		self.chkout_new_serial.setObjectName(_fromUtf8("chkout_new_serial"))
		self.chkout_new_serial_in = QtGui.QLineEdit(self.tab_2)
		self.chkout_new_serial_in.setGeometry(QtCore.QRect(170, 190, 252, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkout_new_serial_in.setFont(font)
		self.chkout_new_serial_in.setObjectName(_fromUtf8("chkout_new_serial_in"))
		self.chkout_new_serial_in.setValidator(self.validator)
		self.chkout_new_asset = QtGui.QLabel(self.tab_2)
		self.chkout_new_asset.setGeometry(QtCore.QRect(440, 190, 171, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkout_new_asset.setFont(font)
		self.chkout_new_asset.setObjectName(_fromUtf8("chkout_new_asset"))
		self.chkout_new_asset_in = QtGui.QLineEdit(self.tab_2)
		self.chkout_new_asset_in.setGeometry(QtCore.QRect(630, 190, 271, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkout_new_asset_in.setFont(font)
		self.chkout_new_asset_in.setObjectName(_fromUtf8("chkout_new_asset_in"))
		self.chkout_new_asset_in.setValidator(self.validator)
		self.chkout_new_descr = QtGui.QLabel(self.tab_2)
		self.chkout_new_descr.setGeometry(QtCore.QRect(30, 250, 164, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkout_new_descr.setFont(font)
		self.chkout_new_descr.setObjectName(_fromUtf8("chkout_new_descr"))
		self.chkout_new_descr_in = QtGui.QLineEdit(self.tab_2)
		self.chkout_new_descr_in.setGeometry(QtCore.QRect(210, 250, 691, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkout_new_descr_in.setFont(font)
		self.chkout_new_descr_in.setObjectName(_fromUtf8("chkout_new_descr_in"))
		self.chkout_new_descr_in.setValidator(self.validator)
		self.chkout_new_submit = QtGui.QPushButton(self.tab_2)
		self.chkout_new_submit.setGeometry(QtCore.QRect(30, 300, 127, 37))
		self.chkout_new_submit.setObjectName(_fromUtf8("chkout_new_submit"))
		self.chkout_new_submit.clicked.connect(core.new_submit_chkout)
# End check out new registered user ------------------------------------------^		
		self.chkout_divider = QtGui.QFrame(self.tab_2)
		self.chkout_divider.setGeometry(QtCore.QRect(10, 350, 911, 16))
		self.chkout_divider.setFrameShape(QtGui.QFrame.HLine)
		self.chkout_divider.setFrameShadow(QtGui.QFrame.Sunken)
		self.chkout_divider.setObjectName(_fromUtf8("chkout_divider"))
# Check out regular registered user ------------------------------------------v
		self.chkout_reg_title = QtGui.QLabel(self.tab_2)
		self.chkout_reg_title.setGeometry(QtCore.QRect(30, 380, 728, 40))
		font = QtGui.QFont()
		font.setPointSize(25)
		font.setBold(True)
		font.setWeight(75)
		self.chkout_reg_title.setFont(font)
		self.chkout_reg_title.setObjectName(_fromUtf8("chkout_reg_title"))
		self.chkout_reg_name = QtGui.QLabel(self.tab_2)
		self.chkout_reg_name.setGeometry(QtCore.QRect(30, 440, 89, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkout_reg_name.setFont(font)
		self.chkout_reg_name.setObjectName(_fromUtf8("chkout_reg_name"))
		self.chkout_drpmn_name = QtGui.QComboBox(self.tab_2)
		self.chkout_drpmn_name.setGeometry(QtCore.QRect(140, 440, 351, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkout_drpmn_name.setFont(font)
		self.chkout_drpmn_name.setObjectName(_fromUtf8("chkout_drpmn_name"))
		self.chkout_drpmn_name.setCurrentIndex(-1)
		self.connect(self.chkout_drpmn_name, QtCore.SIGNAL('currentIndexChanged(int)'), core.chkout_reg_autofill)
		self.chkout_reg_device = QtGui.QLabel(self.tab_2)
		self.chkout_reg_device.setGeometry(QtCore.QRect(30, 500, 100, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkout_reg_device.setFont(font)
		self.chkout_reg_device.setObjectName(_fromUtf8("chkout_reg_device"))
		self.chkout_reg_device_in = QtGui.QLineEdit(self.tab_2)
		self.chkout_reg_device_in.setGeometry(QtCore.QRect(150, 500, 741, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkout_reg_device_in.setFont(font)
		self.chkout_reg_device_in.setObjectName(_fromUtf8("chkout_reg_device_in"))
		self.chkout_reg_device_in.setValidator(self.validator)
		self.chkout_reg_serial = QtGui.QLabel(self.tab_2)
		self.chkout_reg_serial.setGeometry(QtCore.QRect(30, 560, 117, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkout_reg_serial.setFont(font)
		self.chkout_reg_serial.setObjectName(_fromUtf8("chkout_reg_serial"))
		self.chkout_reg_serial_in = QtGui.QLineEdit(self.tab_2)
		self.chkout_reg_serial_in.setGeometry(QtCore.QRect(170, 560, 261, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkout_reg_serial_in.setFont(font)
		self.chkout_reg_serial_in.setObjectName(_fromUtf8("chkout_reg_serial_in"))
		self.chkout_reg_serial_in.setValidator(self.validator)
		self.chkout_reg_asset = QtGui.QLabel(self.tab_2)
		self.chkout_reg_asset.setGeometry(QtCore.QRect(450, 560, 171, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkout_reg_asset.setFont(font)
		self.chkout_reg_asset.setObjectName(_fromUtf8("chkout_reg_asset"))
		self.chkout_reg_asset_in = QtGui.QLineEdit(self.tab_2)
		self.chkout_reg_asset_in.setGeometry(QtCore.QRect(640, 560, 251, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkout_reg_asset_in.setFont(font)
		self.chkout_reg_asset_in.setObjectName(_fromUtf8("chkout_reg_asset_in"))
		self.chkout_reg_asset_in.setValidator(self.validator)
		self.chkout_reg_descr = QtGui.QLabel(self.tab_2)
		self.chkout_reg_descr.setGeometry(QtCore.QRect(30, 620, 164, 33))
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.chkout_reg_descr.setFont(font)
		self.chkout_reg_descr.setObjectName(_fromUtf8("chkout_reg_descr"))
		self.chkout_reg_descr_in = QtGui.QLineEdit(self.tab_2)
		self.chkout_reg_descr_in.setGeometry(QtCore.QRect(210, 620, 681, 39))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.chkout_reg_descr_in.setFont(font)
		self.chkout_reg_descr_in.setObjectName(_fromUtf8("chkout_reg_descr_in"))
		self.chkout_reg_descr_in.setValidator(self.validator)
		self.chkout_reg_descr_in.setValidator(self.validator)
		self.chkout_reg_submit = QtGui.QPushButton(self.tab_2)
		self.chkout_reg_submit.setGeometry(QtCore.QRect(30, 670, 127, 37))
		self.chkout_reg_submit.setObjectName(_fromUtf8("chkout_reg_submit"))
		self.chkout_reg_submit.clicked.connect(core.reg_submit_chkout)
# End check out regular registered user ------------------------------------------^
		self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
		self.dir_button = QtGui.QPushButton(self.centralwidget)
		self.dir_button.setGeometry(QtCore.QRect(10, 780, 186, 41))
		self.dir_button.setMinimumSize(QtCore.QSize(186, 41))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.dir_button.setFont(font)
		self.dir_button.setObjectName(_fromUtf8("dir_button"))
		self.dir_button.clicked.connect(core.open_directory)
		self.close_button = QtGui.QPushButton(self.centralwidget)
		self.close_button.setGeometry(QtCore.QRect(210, 780, 144, 41))
		self.close_button.setMinimumSize(QtCore.QSize(144, 41))
		font = QtGui.QFont()
		font.setPointSize(20)
		self.close_button.setFont(font)
		self.close_button.setObjectName(_fromUtf8("close_button"))
		self.close_button.clicked.connect(QtCore.QCoreApplication.instance().quit)
		self.chkin_img_3 = QtGui.QLabel(self.centralwidget)
		self.chkin_img_3.setGeometry(QtCore.QRect(950, 50, 311, 191))
		self.chkin_img_3.setMinimumSize(QtCore.QSize(311, 191))
		self.chkin_img_3.setText(_fromUtf8(""))
		self.chkin_img_3.setPixmap(QtGui.QPixmap(_fromUtf8("images\logo.jpg")))
		self.chkin_img_3.setScaledContents(True)
		self.chkin_img_3.setObjectName(_fromUtf8("chkin_img_3"))
		self.support_lbl = QtGui.QLabel(self.centralwidget)
		self.support_lbl.setGeometry(QtCore.QRect(950, 310, 205, 19))
		self.support_lbl.setMinimumSize(QtCore.QSize(205, 19))
		font = QtGui.QFont()
		font.setPointSize(12)
		self.support_lbl.setFont(font)
		self.support_lbl.setObjectName(_fromUtf8("support_lbl"))
		self.version_lbl = QtGui.QLabel(self.centralwidget)
		self.version_lbl.setGeometry(QtCore.QRect(950, 270, 270, 19))
		self.version_lbl.setMinimumSize(QtCore.QSize(270, 19))
		font = QtGui.QFont()
		font.setPointSize(12)
		self.version_lbl.setFont(font)
		self.version_lbl.setObjectName(_fromUtf8("version_lbl"))
		self.tooltip_box = QtGui.QTextBrowser(self.centralwidget)
		self.tooltip_box.setGeometry(QtCore.QRect(950, 370, 321, 391))
		self.tooltip_box.setMinimumSize(QtCore.QSize(321, 391))
		font = QtGui.QFont()
		font.setPointSize(12)
		self.tooltip_box.setFont(font)
		self.tooltip_box.setObjectName(_fromUtf8("tooltip_box"))
		byodchkn.setCentralWidget(self.centralwidget)
		self.menubar = QtGui.QMenuBar(byodchkn)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1291, 21))
		self.menubar.setObjectName(_fromUtf8("menubar"))
		byodchkn.setMenuBar(self.menubar)
		self.statusbar = QtGui.QStatusBar(byodchkn)
		self.statusbar.setObjectName(_fromUtf8("statusbar"))
		byodchkn.setStatusBar(self.statusbar)
		self.retranslateUi(byodchkn)
		self.tabWidget.setCurrentIndex(0)
		#QtCore.QMetaObject.connectSlotsByName(byodchkn)

	def retranslateUi(self, byodchkn):
		byodchkn.setWindowTitle(_translate("byodchkn", "byodchkn", None))
		self.chkin_new_title.setText(_translate("byodchkn", "CHECK IN NEW VISITOR/EMPLOYEE", None))
		self.chkin_reg_title.setText(_translate("byodchkn", "CHECK IN FREQUENT VISITOR/EMPLOYEE", None))
		self.chkin_new_name.setText(_translate("byodchkn", "Name:", None))
		self.chkin_new_device.setText(_translate("byodchkn", "Device:", None))
		self.chkin_new_serial.setText(_translate("byodchkn", "Serial #:", None))
		self.chkin_new_descr.setText(_translate("byodchkn", "Description:", None))
		self.chkin_new_asset.setText(_translate("byodchkn", "Asset Tag #:", None))
		self.chkin_reg_descr.setText(_translate("byodchkn", "Description:", None))
		self.chkin_reg_asset.setText(_translate("byodchkn", "Asset Tag #:", None))
		self.chkin_reg_device.setText(_translate("byodchkn", "Device:", None))
		self.chkin_reg_serial.setText(_translate("byodchkn", "Serial #:", None))
		self.chkin_reg_name.setText(_translate("byodchkn", "Name:", None))
		self.chkin_new_submit.setText(_translate("byodchkn", "Submit", None))
		self.chkin_reg_submit.setText(_translate("byodchkn", "Submit", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("byodchkn", "Check In", None))
		self.chkout_reg_device.setText(_translate("byodchkn", "Device:", None))
		self.chkout_reg_descr.setText(_translate("byodchkn", "Description:", None))
		self.chkout_new_serial.setText(_translate("byodchkn", "Serial #:", None))
		self.chkout_reg_name.setText(_translate("byodchkn", "Name:", None))
		self.chkout_new_submit.setText(_translate("byodchkn", "Submit", None))
		self.chkout_reg_asset.setText(_translate("byodchkn", "Asset Tag #:", None))
		self.chkout_reg_submit.setText(_translate("byodchkn", "Submit", None))
		self.chkout_new_device.setText(_translate("byodchkn", "Device:", None))
		self.chkout_reg_serial.setText(_translate("byodchkn", "Serial #:", None))
		self.chkout_new_descr.setText(_translate("byodchkn", "Description:", None))
		self.chkout_new_name.setText(_translate("byodchkn", "Name:", None))
		self.chkout_new_asset.setText(_translate("byodchkn", "Asset Tag #:", None))
		self.chkout_new_title.setText(_translate("byodchkn", "CHECK OUT NEW VISITOR/EMPLOYEE", None))
		self.chkout_reg_title.setText(_translate("byodchkn", "CHECK OUT FREQUENT VISITOR/EMPLOYEE", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("byodchkn", "Check Out", None))
		self.dir_button.setText(_translate("byodchkn", "Open Directory", None))
		self.close_button.setText(_translate("byodchkn", "Close", None))
		self.support_lbl.setText(_translate("byodchkn", "Support: email@email.com", None))
		self.version_lbl.setText(_translate("byodchkn", "BYOD Check In v0.1", None))
		self.tooltip_box.setHtml(_translate("byodchkn", "Placeholder", None))